// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oevzywpcnemdeyuofhjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ldnp5d3BjbmVtZGV5dW9maGpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDQwMjIsImV4cCI6MjA2ODY4MDAyMn0.GiQzidKKEBsaePZQGp23bOVmPQO1fSeSypAaSa5x8XU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});